2021-05-10 13:35:17.063 | ERROR    | utils.logg:error:39 - NoneType: None

2021-05-10 14:29:06.505 | ERROR    | utils.logg:error:39 - 第2行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 113, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AssertionError

2021-05-10 16:03:53.906 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:04:17.845 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:13:33.966 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:13:54.564 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:14:15.244 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:14:35.485 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:14:55.909 | ERROR    | utils.logg:error:39 - 第7行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 124, in assert_ele
    assert values == find_element(driver,ele_type,ele_vaule).text
AttributeError: 'NoneType' object has no attribute 'text'

2021-05-10 16:51:54.361 | ERROR    | utils.logg:error:39 - 第8行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 114, in assert_b_url
    assert values in driver.current_url
AssertionError

2021-05-10 16:51:55.453 | ERROR    | utils.logg:error:39 - 第8行用例断言错误
Traceback (most recent call last):
  File "C:\huang111\tumi-cn\action\eleAction.py", line 114, in assert_b_url
    assert values in driver.current_url
AssertionError

